version: '3.7'

services:
  selenium-hub:
    image: selenium/hub:3.141.59
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - GRID_MAX_SESSION=3

  chrome_latest:
    image: selenium/node-chrome-debug:3.141.59
    restart: always
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_SESSION=1
    ports:
      - 5501:5501
    shm_size: 1gb

  chrome_old1:
    image: selenium/node-chrome-debug:3.141.59-20200326
    restart: always
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_SESSION=1
    ports:
      - 5502:5502
    shm_size: 1gb

  chrome_old2:
    image: selenium/node-chrome-debug:3.141.59-neon
    restart: always
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_SESSION=1
    ports:
      - 5503:5503
    shm_size: 1gb